### ISSUE TITLE
Can you tell me how to get these game data?

### ISSUE THREAD

**Issue by MatchaC** [CatClawed/barrelwisdom#14]
I plan to build an Atelier Series Wiki in my country.
Now Working on the progress of analysis A23 unpack files.
I noticed that the XML data is basically in the saves folder,but I can't find the correlation between some files.
Such as Effect, names in 'saves/text_lang/str_item_effect.xml',describes in 'saves/text_lang/str_library_eff_detail.xml',details in 'saves/item/item_effect.xml'.
But item mix data in 'saves/item/itemrecipedata.xml' seems to be no direct correlation with effect data，like ITEM_EFF_CRAFT_02_01 and ITEM_EFFECT_0122.
It looks like there should has a middle table, but I just can't find it
When I was at a loss, I saw your website and marveled at the completion.
Do you record the data manually or through analysis?
If it is the latter, I would appreciate it if you could give me some tips

**Comment by CatClawed** [comment]
This isn't a trivial process (and I would not be surprised if there was a better way), but I'll outline what I do.

First step, I run [this script](https://github.com/CatClawed/janky-website-scripts/blob/master/enum_utils/enum_finder.py) to find all the enums from within the game's executable. It does not find everything. I attempt to insert the missing values with [this](https://github.com/CatClawed/janky-website-scripts/blob/master/enum_utils/enum_inserter.py), but it's not a perfect script and requires a human touch to fix some stuff.

After, I run [this](https://github.com/CatClawed/janky-website-scripts/blob/master/XML_enums/Atelier_align_xml_enums.py) on the localization files. It inserts blank lines where there are skips in the string IDs; these gaps are actually notable. The enums do not line up if you do not include the gaps.

After that, I line up effects and relevant enums (they will be in order) side by side. This ultimately takes some trial and error; the steps outlined above will get you most of the way there, but there will be issues with them lining up and you'll have to do some manual adjustments.

**Comment by MatchaC** [comment]
> This isn't a trivial process (and I would not be surprised if there was a better way), but I'll outline what I do.
> 
> First step, I run [this script](https://github.com/CatClawed/janky-website-scripts/blob/master/enum_utils/enum_finder.py) to find the enums from within the game's executable. It does not find everything. I attempt to insert the missing values with [this](https://github.com/CatClawed/janky-website-scripts/blob/master/enum_utils/enum_inserter.py), but it's not a perfect script and requires a human touch to fix some stuff.
> 
> After, I run [this](https://github.com/CatClawed/janky-website-scripts/blob/master/XML_enums/Atelier_align_xml_enums.py) on the localization files. It inserts blank lines where there are skips in the string IDs; these gaps are actually notable. The enums do not line up if you do not include the gaps.
> 
> After that, I line up effects and relevant enums (they will be in order) side by side. This ultimately takes some trial and error; the steps outlined above will get you most of the way there, but there will be issues with them lining up and you'll have to do some manual adjustments.

 I refer to your method and have made great progress.
Thank you verrrry much!!!!!!!!!!!
