### ISSUE TITLE
Items not filterable when changed language on A18 items page 

### ISSUE THREAD

**Issue by Paper-Folding** [CatClawed/barrelwisdom#63]
Hi, dear developers:
    Recently I've been playing Atelier Firis DX and found your site amazing!  
    As a Chinese player, I also found your site does support Chinese localization! That's wonderful! But I found a bug that I cannot filter items by category on this page: https://barrelwisdom.com/firis/items/sc , it might because the category options did not translated.  
So could you please fix this?

**Comment by CatClawed** [comment]
Thank you for the report! The site has been updated with the translations.
